[package]
name = "graphql"
version = "0.1.0"
authors = ["Danuel <public.danuel@gmail.com>"]
edition = "2018"

[dependencies]
graphql-parser = { path = "graphql-parser" }

[workspace]
members = [
  "graphql-parser"
]
